import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const communityTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Community',
    es: 'Comunidad',
    fr: 'Communauté',
    de: 'Gemeinschaft',
    it: 'Comunità',
    pt: 'Comunidade',
    ru: 'Сообщество',
    'zh-CN': '社区',
    da: 'Fællesskab',
    hi: 'समुदाय',
    id: 'Komunitas',
    ja: 'コミュニティ',
    ko: '커뮤니티',
    'pt-BR': 'Comunidade',
    'pt-PT': 'Comunidade',
    tr: 'Topluluk',
    uk: 'Спільнота',
  },
  link: '/community/',
  icon: 'heart',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Resumen',
        fr: 'Aperçu',
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        pt: 'Visão geral',
        'pt-BR': 'Visão geral',
        'pt-PT': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'community',
    },
    {
      label: 'Contributors',
      translations: {
        da: 'Bidragydere',
        de: 'Mitwirkende',
        en: 'Contributors',
        es: 'Colaboradores',
        fr: 'Contributeurs',
        hi: 'योगदानकर्ता',
        id: 'Kontributor',
        it: 'Collaboratori',
        ja: 'コントリビューター',
        ko: '기여자',
        pt: 'Contribuidores',
        'pt-BR': 'Contribuidores',
        'pt-PT': 'Contribuidores',
        ru: 'Участники',
        tr: 'Katkıda Bulunanlar',
        uk: 'Учасники',
        'zh-CN': '贡献者',
      },
      items: [
        {
          label: 'Contributor overview',
          translations: {
            da: 'Oversigt over bidragydere',
            de: 'Übersicht der Mitwirkenden',
            en: 'Contributor overview',
            es: 'Descripción general del colaborador',
            fr: 'Aperçu des contributeurs',
            hi: 'योगदानकर्ता अवलोकन',
            id: 'Ikhtisar kontributor',
            it: 'Panoramica dei collaboratori',
            ja: 'コントリビューターの概要',
            ko: '기여자 개요',
            pt: 'Visão geral do contribuinte',
            'pt-BR': 'Visão geral do contribuinte',
            'pt-PT': 'Visão geral do contribuinte',
            ru: 'Обзор участников',
            tr: 'Katkıda Bulunanlar Genel Bakışı',
            uk: 'Огляд учасників',
            'zh-CN': '贡献者概述',
          },
          slug: 'community/contributors',
        },
        {
          label: 'Contributor guide',
          translations: {
            da: 'Bidragydervejledning',
            de: 'Mitwirkenden-Leitfaden',
            en: 'Contributor guide',
            es: 'Guía del colaborador',
            fr: 'Guide du contributeur',
            hi: 'योगदानकर्ता गाइड',
            id: 'Panduan kontributor',
            it: 'Guida per i collaboratori',
            ja: 'コントリビューターガイド',
            ko: '기여자 가이드',
            pt: 'Guia do contribuinte',
            'pt-BR': 'Guia do contribuinte',
            'pt-PT': 'Guia do contribuinte',
            ru: 'Руководство для участников',
            tr: 'Katkıda Bulunanlar Kılavuzu',
            uk: 'Посібник для учасників',
            'zh-CN': '贡献者指南',
          },
          slug: 'community/contributor-guide',
        },
      ],
    },
    {
      label: 'BlueSky',
      slug: 'community/posts',
      badge: {
        text: '#aspire',
        variant: 'note',
      },
    },
    {
      label: 'Videos',
      translations: {
        da: 'Videoer',
        de: 'Videos',
        en: 'Videos',
        es: 'Videos',
        fr: 'Vidéos',
        hi: 'वीडियो',
        id: 'Video',
        it: 'Video',
        ja: '動画',
        ko: '비디오',
        pt: 'Vídeos',
        'pt-BR': 'Vídeos',
        'pt-PT': 'Vídeos',
        ru: 'Видео',
        tr: 'Videolar',
        uk: 'Відео',
        'zh-CN': '视频',
      },
      slug: 'community/videos',
    },
    {
      label: 'Aspire Conf',
      slug: 'aspireconf',
      badge: {
        text: 'Mar 23',
        variant: 'tip',
      },
    },
  ],
};
