import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const docsTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    da: 'Dokumenter',
    de: 'Dokumente',
    en: 'Docs',
    es: 'Documentos',
    fr: 'Documents',
    hi: 'दस्तावेज़',
    id: 'Dokumen',
    it: 'Documenti',
    ja: 'ドキュメント',
    ko: '문서',
    'pt-BR': 'Documentos',
    'pt-PT': 'Documentos',
    ru: 'Документы',
    tr: 'Belgeler',
    uk: 'Документи',
    'zh-CN': '文档',
  },
  link: 'docs',
  icon: 'open-book',
  items: [
    {
      label: 'Welcome to Aspire',
      translations: {
        da: 'Velkommen til Aspire',
        de: 'Willkommen bei Aspire',
        en: 'Welcome to Aspire',
        es: 'Bienvenido a Aspire',
        fr: 'Bienvenue à Aspire',
        hi: 'Aspire में आपका स्वागत है',
        id: 'Selamat datang di Aspire',
        it: 'Benvenuto in Aspire',
        ja: 'Aspire へようこそ',
        ko: 'Aspire에 오신 것을 환영합니다',
        'pt-BR': 'Bem-vindo ao Aspire',
        'pt-PT': 'Bem-vindo ao Aspire',
        ru: 'Добро пожаловать в Aspire',
        tr: "Aspire'a Hoş Geldiniz",
        uk: 'Ласкаво просимо до Aspire',
        'zh-CN': '欢迎使用 Aspire',
      },
      slug: 'docs',
    },
    {
      label: "What's new",
      collapsed: true,
      items: [
        {
          label: 'Aspire 13.1',
          slug: 'whats-new/aspire-13-1'
        },
        {
          label: 'Aspire 13.0',
          slug: 'whats-new/aspire-13'
        },
        {
          label: 'Previous versions',
          collapsed: true,
          translations: {
            da: 'Tidligere versioner',
            de: 'Frühere Versionen',
            en: 'Previous versions',
            es: 'Versiones anteriores',
            fr: 'Versions précédentes',
            hi: 'पिछले संस्करण',
            id: 'Versi sebelumnya',
            it: 'Versioni precedenti',
            ja: '以前のバージョン',
            ko: '이전 버전',
            'pt-BR': 'Versões anteriores',
            'pt-PT': 'Versões anteriores',
            ru: 'Предыдущие версии',
            tr: 'Önceki sürümler',
            uk: 'Попeredні версії',
            'zh-CN': '以前的版本',
          },
          items: [
            {
              label: 'Aspire 9.5',
              slug: 'whats-new/aspire-9-5'
            },
            {
              label: 'Aspire 9.4',
              slug: 'whats-new/aspire-9-4'
            },
            {
              label: 'Aspire 9.3',
              slug: 'whats-new/aspire-9-3'
            },
            {
              label: 'Aspire 9.2',
              slug: 'whats-new/aspire-9-2'
            },
            {
              label: 'Aspire 9.1',
              slug: 'whats-new/aspire-9-1'
            },
            {
              label: 'Aspire 9.0',
              slug: 'whats-new/aspire-9'
            },
          ],
        },
        {
          label: 'Upgrade Aspire',
          slug: 'whats-new/upgrade-aspire',
          translations: {
            da: 'Opgrader Aspire',
            de: 'Aspire aktualisieren',
            en: 'Upgrade Aspire',
            es: 'Actualizar Aspire',
            fr: 'Mettre à jour Aspire',
            hi: 'Aspire अपग्रेड करें',
            id: 'Tingkatkan Aspire',
            it: 'Aggiorna Aspire',
            ja: 'Aspire をアップグレード',
            ko: 'Aspire 업그레이드',
            'pt-BR': 'Atualizar Aspire',
            'pt-PT': 'Atualizar Aspire',
            ru: 'Обновить Aspire',
            tr: "Aspire'ı Yükselt",
            uk: 'Оновити Aspire',
            'zh-CN': '升级 Aspire',
          },
        },
      ],
      translations: {
        da: 'Hvad er nyt',
        de: 'Was gibt es Neues',
        en: "What's new",
        es: 'Novedades',
        fr: 'Quoi de neuf',
        hi: 'क्या नया है',
        id: 'Apa yang baru',
        it: 'Novità',
        ja: '新着情報',
        ko: '새로운 소식',
        'pt-BR': 'Novidades',
        'pt-PT': 'Novidades',
        ru: 'Что нового',
        tr: 'Yeni neler var',
        uk: 'Що нового',
        'zh-CN': '新内容',
      },
    },
    {
      label: 'Get started',
      translations: {
        da: 'Kom godt i gang',
        de: 'Erste schritte',
        en: 'Get started',
        es: 'Empezar',
        fr: 'Commencer',
        hi: 'शुरू करें',
        id: 'Mulai',
        it: 'Iniziare',
        ja: '始める',
        ko: '시작하기',
        'pt-BR': 'Começar',
        'pt-PT': 'Começar',
        ru: 'Начать',
        tr: 'Başlamak',
        uk: 'Розпочати',
        'zh-CN': '开始',
      },
      items: [
        {
          label: 'Setup and tooling',
          collapsed: true,
          translations: {
            da: 'Opsætning og værktøjer',
            de: 'Einrichtung und Werkzeuge',
            en: 'Setup and tooling',
            es: 'Configuración y herramientas',
            fr: 'Configuration et outils',
            hi: 'सेटअप और टूलिंग',
            id: 'Pengaturan dan alat',
            it: 'Configurazione e strumenti',
            ja: 'セットアップとツール',
            ko: '설정 및 도구',
            'pt-BR': 'Configuração e ferramentas',
            'pt-PT': 'Configuração e ferramentas',
            ru: 'Настройка и инструменты',
            tr: 'Kurulum ve araçlar',
            uk: 'Налаштування та інструменти',
            'zh-CN': '设置和工具',
          },
          items: [
            {
              label: 'Prerequisites',
              translations: {
                da: 'Forudsætninger',
                de: 'Voraussetzungen',
                en: 'Prerequisites',
                es: 'Requisitos previos',
                fr: 'Prérequis',
                hi: 'पूर्वापेक्षाएँ',
                id: 'Prasyarat',
                it: 'Prerequisiti',
                ja: '事前準備',
                ko: '전제 조건',
                'pt-BR': 'Pré-requisitos',
                'pt-PT': 'Pré-requisitos',
                ru: 'Предварительные требования',
                tr: 'Ön koşullar',
                uk: 'Попередні вимоги',
                'zh-CN': '先决条件',
              },
              slug: 'get-started/prerequisites',
            },
            {
              label: 'Install CLI',
              translations: {
                da: 'Installer CLI',
                de: 'CLI installieren',
                en: 'Install CLI',
                es: 'Instalar CLI',
                fr: 'Installer CLI',
                hi: 'CLI इंस्टॉल करें',
                id: 'Instal CLI',
                it: 'Installa CLI',
                ja: 'CLI をインストールする',
                ko: 'CLI 설치',
                'pt-BR': 'Instalar CLI',
                'pt-PT': 'Instalar CLI',
                ru: 'Установить CLI',
                tr: 'CLI Kur',
                uk: 'Встановити CLI',
                'zh-CN': '安装 CLI',
              },
              slug: 'get-started/install-cli',
            },
            {
              label: 'VS Code extension',
              translations: {
                da: 'VS Code-udvidelse',
                de: 'VS Code-Erweiterung',
                en: 'VS Code extension',
                es: 'Extensión de VS Code',
                fr: 'Extension VS Code',
                hi: 'VS Code एक्सटेंशन',
                id: 'Ekstensi VS Code',
                it: 'Estensione VS Code',
                ja: 'VS Code 拡張機能',
                ko: 'VS Code 확장',
                'pt-BR': 'Extensão VS Code',
                'pt-PT': 'Extensão VS Code',
                ru: 'Расширение VS Code',
                tr: 'VS Code uzantısı',
                uk: 'Розширення VS Code',
                'zh-CN': 'VS Code 扩展',
              },
              slug: 'get-started/aspire-vscode-extension',
            },
            {
              label: 'Dev Containers',
              slug: 'get-started/dev-containers',
            },
            {
              label: 'GitHub Codespaces',
              slug: 'get-started/github-codespaces',
            },
            {
              label: 'Aspire SDK',
              slug: 'get-started/aspire-sdk',
            },
            {
              label: 'Aspire templates',
              translations: {
                da: 'Aspire-skabeloner',
                de: 'Aspire-Vorlagen',
                en: 'Aspire templates',
                es: 'Plantillas de Aspire',
                fr: 'Modèles Aspire',
                hi: 'Aspire टेम्प्लेट',
                id: 'Template Aspire',
                it: 'Modelli Aspire',
                ja: 'Aspire テンプレート',
                ko: 'Aspire 템플릿',
                'pt-BR': 'Modelos do Aspire',
                'pt-PT': 'Modelos do Aspire',
                ru: 'Шаблоны Aspire',
                tr: 'Aspire şablonları',
                uk: 'Шаблони Aspire',
                'zh-CN': 'Aspire 模板',
              },
              slug: 'get-started/aspire-sdk-templates',
            },
          ],
        },
        {
          label: 'Build your first app',
          translations: {
            da: 'Byg din første app',
            de: 'Erstellen Sie Ihre erste App',
            en: 'Build your first app',
            es: 'Construye tu primera app',
            fr: 'Construisez votre première application',
            hi: 'अपना पहला ऐप बनाएं',
            id: 'Bangun aplikasi pertama Anda',
            it: 'Crea la tua prima app',
            ja: '最初のアプリを作成する',
            ko: '첫 번째 앱 만들기',
            'pt-BR': 'Construa seu primeiro app',
            'pt-PT': 'Construa a sua primeira app',
            ru: 'Создайте свое первое приложение',
            tr: 'İlk uygulamanızı oluşturun',
            uk: 'Створіть свій перший додаток',
            'zh-CN': '构建您的第一个应用',
          },
          slug: 'get-started/first-app',
          badge: {
            text: 'Quickstart',
            variant: 'tip',
            translations: {
              da: 'Hurtigstart',
              de: 'Schnellstart',
              en: 'Quickstart',
              es: 'Inicio rápido',
              fr: 'Démarrage rapide',
              hi: 'त्वरित आरंभ',
              id: 'Memulai Cepat',
              it: 'Avvio rapido',
              ja: 'クイックスタート',
              ko: '빠른 시작',
              'pt-BR': 'Início Rápido',
              'pt-PT': 'Início Rápido',
              ru: 'Быстрый старт',
              tr: 'Hızlı Başlangıç',
              uk: 'Швидкий старт',
              'zh-CN': '快速开始',
            },
          },
        },
        {
          label: 'Deploy your first app',
          translations: {
            da: 'Udrul din første app',
            de: 'Bereitstellung Ihrer ersten App',
            en: 'Deploy your first app',
            es: 'Despliega tu primera app',
            fr: 'Déployez votre première application',
            hi: 'अपना पहला ऐप तैनात करें',
            id: 'Deploy aplikasi pertama Anda',
            it: 'Distribuisci la tua prima app',
            ja: '最初のアプリをデプロイする',
            ko: '첫 번째 앱 배포',
            'pt-BR': 'Implante seu primeiro app',
            'pt-PT': 'Implemente a sua primeira app',
            ru: 'Разверните свое первое приложение',
            tr: 'İlk uygulamanızı dağıtın',
            uk: 'Розгорніть свій перший додаток',
            'zh-CN': '部署您的第一个应用',
          },
          slug: 'get-started/deploy-first-app',
          badge: {
            text: 'Tutorial',
            variant: 'success',
            translations: {
              da: 'Vejledning',
              de: 'Anleitung',
              en: 'Tutorial',
              es: 'Tutorial',
              fr: 'Tutoriel',
              hi: 'ट्यूटोरियल',
              id: 'Tutorial',
              it: 'Tutorial',
              ja: 'チュートリアル',
              ko: '튜토리얼',
              'pt-BR': 'Tutorial',
              'pt-PT': 'Tutorial',
              ru: 'Учебник',
              tr: 'Eğitim',
              uk: 'Підручник',
            },
          },
        },
        {
          label: 'Aspireify an existing app',
          translations: {
            da: 'Aspireify en eksisterende app',
            de: 'Eine bestehende App Aspireify',
            en: 'Aspireify an existing app',
            es: 'Aspireify una aplicación existente',
            fr: 'Aspireify une application existante',
            hi: 'मौजूदा ऐप को Aspireify करें',
            id: 'Aspireify aplikasi yang sudah ada',
            it: "Aspireify un'app esistente",
            ja: '既存のアプリを Aspireify する',
            ko: '기존 앱을 Aspireify하기',
            'pt-BR': 'Aspireify um app existente',
            'pt-PT': 'Aspireify uma app existente',
            ru: 'Aspireify существующее приложение',
            tr: 'Mevcut bir uygulamayı Aspireify et',
            uk: 'Aspireify наявний застосунок',
            'zh-CN': '对现有应用进行 Aspireify',
          },
          slug: 'get-started/add-aspire-existing-app',
        },
        {
          label: 'Configure the MCP server',
          translations: {
            da: 'Konfigurer MCP-serveren',
            de: 'MCP-Server konfigurieren',
            en: 'Configure the MCP server',
            es: 'Configurar el servidor MCP',
            fr: 'Configurer le serveur MCP',
            hi: 'MCP सर्वर कॉन्फ़िगर करें',
            id: 'Konfigurasi server MCP',
            it: 'Configurare il server MCP',
            ja: 'MCP サーバーの構成',
            ko: 'MCP 서버 구성',
            'pt-BR': 'Configurar o servidor MCP',
            'pt-PT': 'Configurar o servidor MCP',
            ru: 'Настройка сервера MCP',
            tr: 'MCP sunucusunu yapılandırın',
            uk: 'Налаштування сервера MCP',
            'zh-CN': '配置 MCP 服务器',
          },
          slug: 'get-started/configure-mcp',
        },
      ],
    },
    {
      label: 'Fundamentals',
      collapsed: true,
      translations: {
        da: 'Begreber',
        de: 'Grundlagen',
        en: 'Fundamentals',
        es: 'Fundamentos',
        fr: 'Notions fondamentales',
        hi: 'मूल बातें',
        id: 'Dasar-dasar',
        it: 'Fondamenti',
        ja: '基本',
        ko: '기본 사항',
        'pt-BR': 'Fundamentos',
        'pt-PT': 'Fundamentos',
        ru: 'Основы',
        tr: 'Temeller',
        uk: 'Основи',
        'zh-CN': '基础知识',
      },
      items: [
        {
          label: 'What is Aspire?',
          translations: {
            da: 'Hvad er Aspire?',
            de: 'Was ist Aspire?',
            en: 'What is Aspire?',
            es: '¿Qué es Aspire?',
            fr: 'Qu’est-ce qu’Aspire ?',
            hi: 'Aspire क्या है?',
            id: 'Apa itu Aspire?',
            it: 'Che cos’è Aspire?',
            ja: 'Aspire とは何ですか?',
            ko: 'Aspire란 무엇인가요?',
            'pt-BR': 'O que é Aspire?',
            'pt-PT': 'O que é Aspire?',
            ru: 'Что такое Aspire?',
            tr: 'Aspire nedir?',
            uk: 'Що таке Aspire?',
            'zh-CN': 'Aspire 是什么？',
          },
          slug: 'get-started/what-is-aspire',
        },
        {
          label: 'What is the AppHost?',
          translations: {
            da: 'Hvad er AppHost?',
            de: 'Was ist der AppHost?',
            en: 'What is the AppHost?',
            es: '¿Qué es el AppHost?',
            fr: "Qu'est-ce que l’AppHost ?",
            hi: 'AppHost क्या है?',
            id: 'Apa itu AppHost?',
            it: "Che cos'è l’AppHost?",
            ja: 'AppHost とは?',
            ko: 'AppHost란 무엇인가요?',
            'pt-BR': 'O que é o AppHost?',
            'pt-PT': 'O que é o AppHost?',
            ru: 'Что такое AppHost?',
            tr: 'AppHost nedir?',
            uk: 'Що таке AppHost?',
            'zh-CN': '什么是 AppHost？',
          },
          slug: 'get-started/app-host',
        },
        {
          label: 'Understanding resources',
          translations: {
            da: 'Forstå ressourcer',
            de: 'Ressourcen verstehen',
            en: 'Understanding resources',
            es: 'Comprender los recursos',
            fr: 'Comprendre les ressources',
            hi: 'संसाधनों को समझना',
            id: 'Memahami Sumber Daya',
            it: 'Comprendere le risorse',
            ja: 'リソースの理解',
            ko: '리소스 이해',
            'pt-BR': 'Compreendendo os recursos',
            'pt-PT': 'Compreender os recursos',
            ru: 'Понимание ресурсов',
            tr: 'Kaynakları anlama',
            uk: 'Розуміння ресурсів',
            'zh-CN': '了解资源',
          },
          slug: 'get-started/resources',
        },
        {
          label: 'Pipelines and app topology',
          translations: {
            da: 'Udrulning og apptopologi',
            de: 'Bereitstellung und App-Topologie',
            en: 'Pipelines and app topology',
            es: 'Despliegue y topología de la aplicación',
            fr: 'Déploiement et topologie de l’application',
            hi: 'परिनियोजन और ऐप टोपोलॉजी',
            id: 'Penyebaran dan topologi aplikasi',
            it: 'Distribuzione e topologia dell’applicazione',
            ja: 'パイプラインとアプリのトポロジー',
            ko: '배포 및 앱 토폴로지',
            'pt-BR': 'Implantação e topologia do aplicativo',
            'pt-PT': 'Implementação e topologia da aplicação',
            ru: 'Развертывание и топология приложения',
            tr: 'Dağıtım ve uygulama topolojisi',
            uk: 'Розгортання і топологія застосунку',
            'zh-CN': '部署与应用拓扑',
          },
          slug: 'get-started/pipelines',
        },
        {
          label: 'Service discovery',
          translations: {
            da: 'Tjenesteopdagelse',
            de: 'Dienstermittlung',
            en: 'Service discovery',
            es: 'Descubrimiento de servicios',
            fr: 'Découverte de services',
            hi: 'सेवा खोज',
            id: 'Penemuan layanan',
            it: 'Individuazione del servizio',
            ja: 'サービス検出',
            ko: '서비스 검색',
            'pt-BR': 'Descoberta de serviços',
            'pt-PT': 'Descoberta de serviços',
            ru: 'Обнаружение служб',
            tr: 'Hizmet keşfi',
            uk: 'Виявлення служб',
            'zh-CN': '服务发现',
          },
          slug: 'fundamentals/service-discovery',
        },
        {
          label: 'Service defaults',
          translations: {
            da: 'Tjenestestandarder',
            de: 'Dienst-Standardeinstellungen',
            en: 'Service defaults',
            es: 'Valores predeterminados del servicio',
            fr: 'Paramètres par défaut du service',
            hi: 'सेवा डिफ़ॉल्ट',
            id: 'Default layanan',
            it: 'Impostazioni predefinite del servizio',
            ja: 'サービスの既定値',
            ko: '서비스 기본값',
            'pt-BR': 'Padrões de serviço',
            'pt-PT': 'Padrões de serviço',
            ru: 'Значения по умолчанию для служб',
            tr: 'Hizmet varsayılanları',
            uk: 'Значення за замовчуванням служби',
            'zh-CN': '服务默认值',
          },
          slug: 'fundamentals/service-defaults',
        },
        {
          label: 'Launch profiles',
          translations: {
            da: 'Start profiler',
            de: 'Startprofile',
            en: 'Launch profiles',
            es: 'Perfiles de inicio',
            fr: 'Profils de lancement',
            hi: 'लॉन्च प्रोफ़ाइल',
            id: 'Profil peluncuran',
            it: 'Profili di avvio',
            ja: '起動プロファイル',
            ko: '시작 프로필',
            'pt-BR': 'Perfis de inicialização',
            'pt-PT': 'Perfis de inicialização',
            ru: 'Профили запуска',
            tr: 'Başlatma profilleri',
            uk: 'Профілі запуску',
            'zh-CN': '启动配置文件',
          },
          slug: 'fundamentals/launch-profiles',
        },
        {
          label: 'Health checks',
          translations: {
            da: 'Sundhedstjek',
            de: 'Integritätsprüfungen',
            en: 'Health checks',
            es: 'Comprobaciones de estado',
            fr: "Vérifications de l'état",
            hi: 'स्वास्थ्य जांच',
            id: 'Pemeriksaan kesehatan',
            it: 'Controlli di integrità',
            ja: '正常性チェック',
            ko: '상태 확인',
            'pt-BR': 'Verificações de integridade',
            'pt-PT': 'Verificações de integridade',
            ru: 'Проверки работоспособности',
            tr: 'Durum denetimleri',
            uk: 'Перевірки справності',
            'zh-CN': '运行状况检查',
          },
          slug: 'fundamentals/health-checks',
        },
        {
          label: 'Telemetry',
          slug: 'fundamentals/telemetry',
          translations: {
            da: 'Telemetri',
            de: 'Telemetrie',
            en: 'Telemetry',
            es: 'Telemetría',
            fr: 'Télémétrie',
            hi: 'टेलीमेट्री',
            id: 'Telemetri',
            it: 'Telemetria',
            ja: 'テレメトリ',
            ko: '원격 분석',
            'pt-BR': 'Telemetria',
            'pt-PT': 'Telemetria',
            ru: 'Телеметрия',
            tr: 'Telemetri',
            uk: 'Телеметрія',
            'zh-CN': '遥测',
          },
        },
        {
          label: 'Networking overview',
          slug: 'fundamentals/networking-overview',
          translations: {
            da: 'Netværksoverblik',
            de: 'Netzwerkübersicht',
            en: 'Networking overview',
            es: 'Descripción general de redes',
            fr: 'Aperçu du réseau',
            hi: 'नेटवर्किंग अवलोकन',
            id: 'Ikhtisar jaringan',
            it: 'Panoramica della rete',
            ja: 'ネットワーキングの概要',
            ko: '네트워킹 개요',
            'pt-BR': 'Visão geral de rede',
            'pt-PT': 'Visão geral de rede',
            ru: 'Обзор сетевых подключений',
            tr: 'Ağ genel bakışı',
            uk: 'Огляд мережі',
            'zh-CN': '网络概述',
          },
        },
        {
          label: 'External parameters',
          slug: 'fundamentals/external-parameters',
          translations: {
            da: 'Eksterne parametre',
            de: 'Externe Parameter',
            en: 'External parameters',
            es: 'Parámetros externos',
            fr: 'Paramètres externes',
            hi: 'बाहरी पैरामीटर',
            id: 'Parameter eksternal',
            it: 'Parametri esterni',
            ja: '外部パラメーター',
            ko: '외부 매개변수',
            'pt-BR': 'Parâmetros externos',
            'pt-PT': 'Parâmetros externos',
            ru: 'Внешние параметры',
            tr: 'Harici parametreler',
            uk: 'Зовнішні параметри',
            'zh-CN': '外部参数',
          },
        },
        {
          label: 'Persist data with volumes',
          slug: 'fundamentals/persist-data-volumes',
          translations: {
            da: 'Bevar data med volumener',
            de: 'Daten mit Volumes speichern',
            en: 'Persist data with volumes',
            es: 'Persistir datos con volúmenes',
            fr: 'Conserver les données avec des volumes',
            hi: 'वॉल्यूम के साथ डेटा बनाए रखें',
            id: 'Pertahankan data dengan volume',
            it: 'Mantieni i dati con i volumi',
            ja: 'ボリュームでデータを永続化する',
            ko: '볼륨으로 데이터 유지',
            'pt-BR': 'Persistir dados com volumes',
            'pt-PT': 'Persistir dados com volumes',
            ru: 'Сохранение данных с помощью томов',
            tr: 'Verileri hacimlerle kalıcı hale getirin',
            uk: 'Збереження даних за допомогою томів',
            'zh-CN': '使用卷持久化数据',
          },
        },
        {
          label: 'Resource annotations',
          slug: 'fundamentals/annotations-overview',
          translations: {
            da: 'Ressourceannoteringer',
            de: 'Ressourcenanmerkungen',
            en: 'Resource annotations',
            es: 'Anotaciones de recursos',
            fr: 'Annotations de ressources',
            hi: 'संसाधन एनोटेशन',
            id: 'Anotasi sumber daya',
            it: 'Annotazioni delle risorse',
            ja: 'リソース注釈',
            ko: '리소스 주석',
            'pt-BR': 'Anotações de recursos',
            'pt-PT': 'Anotações de recursos',
            ru: 'Аннотации ресурсов',
            tr: 'Kaynak açıklamaları',
            uk: 'Анотації ресурсів',
            'zh-CN': '资源注释',
          },
        },
        {
          label: 'Aspire app lifecycle guide',
          slug: 'fundamentals/app-lifecycle',
          translations: {
            da: 'Guide til Aspire app-livscyklus',
            de: 'Leitfaden zum Aspire-App-Lebenszyklus',
            en: 'Aspire app lifecycle guide',
            es: 'Guía del ciclo de vida de la aplicación Aspire',
            fr: 'Guide du cycle de vie des applications Aspire',
            hi: 'Aspire ऐप जीवनचक्र गाइड',
            id: 'Panduan siklus hidup aplikasi Aspire',
            it: 'Guida al ciclo di vita delle app Aspire',
            ja: 'Aspire アプリのライフサイクル ガイド',
            ko: 'Aspire 앱 수명 주기 가이드',
            'pt-BR': 'Guia do ciclo de vida do aplicativo Aspire',
            'pt-PT': 'Guia do ciclo de vida da aplicação Aspire',
            ru: 'Руководство по жизненному циклу приложения Aspire',
            tr: 'Aspire uygulama yaşam döngüsü kılavuzu',
            uk: 'Посібник з життєвого циклу застосунку Aspire',
            'zh-CN': 'Aspire 应用生命周期指南',
          },
        },
      ],
    },
    {
      label: 'AppHost',
      collapsed: true,
      items: [
        {
          label: 'Configuration',
          slug: 'app-host/configuration',
        },
        {
          label: 'Certificate configuration',
          slug: 'app-host/certificate-configuration',
        },
        {
          label: 'Eventing',
          slug: 'app-host/eventing',
        },
        {
          label: 'Persistent containers',
          slug: 'app-host/persistent-containers',
        },
        {
          label: 'Dockerfiles',
          slug: 'app-host/withdockerfile',
        },
        {
          label: 'Executable resources',
          slug: 'app-host/executable-resources',
        },
        {
          label: 'Migrate from Docker Compose',
          translations: {
            da: 'Migrer fra Docker Compose',
            de: 'Von Docker Compose migrieren',
            en: 'Migrate from Docker Compose',
            es: 'Migrar desde Docker Compose',
            fr: 'Migrer depuis Docker Compose',
            hi: 'Docker Compose से माइग्रेट करें',
            id: 'Migrasi dari Docker Compose',
            it: 'Migrare da Docker Compose',
            ja: 'Docker Compose から移行する',
            ko: 'Docker Compose에서 마이그레이션',
            'pt-BR': 'Migrar do Docker Compose',
            'pt-PT': 'Migrar do Docker Compose',
            ru: 'Миграция с Docker Compose',
            tr: "Docker Compose'dan geçiş yapın",
            uk: 'Міграція з Docker Compose',
            'zh-CN': '从 Docker Compose 迁移',
          },
          slug: 'app-host/migrate-from-docker-compose',
        },
        {
          label: 'Docker Compose to AppHost',
          translations: {
            da: 'Docker Compose til AppHost',
            de: 'Docker Compose zu AppHost',
            en: 'Docker Compose to AppHost',
            es: 'Docker Compose a AppHost',
            fr: 'Docker Compose vers AppHost',
            hi: 'Docker Compose से AppHost तक',
            id: 'Docker Compose ke AppHost',
            it: 'Docker Compose ad AppHost',
            ja: 'Docker Compose から AppHost へ',
            ko: 'Docker Compose에서 AppHost로',
            'pt-BR': 'Docker Compose para AppHost',
            'pt-PT': 'Docker Compose para AppHost',
            ru: 'Docker Compose в AppHost',
            tr: 'Docker Compose to AppHost',
            uk: 'Docker Compose до AppHost',
            'zh-CN': '从 Docker Compose 到 AppHost',
          },
          slug: 'app-host/docker-compose-to-apphost-reference',
        },
      ],
    },
    {
      label: 'Extensibility',
      collapsed: true,
      items: [
        {
          label: 'Interaction service',
          slug: 'extensibility/interaction-service',
        },
        {
          label: 'Custom resource commands',
          slug: 'fundamentals/custom-resource-commands',
        },
        {
          label: 'Custom HTTP commands',
          slug: 'fundamentals/http-commands',
        },
        {
          label: 'Custom resource URLs',
          slug: 'fundamentals/custom-resource-urls',
        },
      ],
    },
    {
      label: 'Testing',
      collapsed: true,
      translations: {
        da: 'Test',
        de: 'Tests',
        en: 'Testing',
        es: 'Pruebas',
        fr: 'Tests',
        hi: 'परीक्षण',
        id: 'Pengujian',
        it: 'Test',
        ja: 'テスト',
        ko: '테스트',
        pt: 'Testes',
        'pt-BR': 'Testes',
        'pt-PT': 'Testes',
        ru: 'Тестирование',
        tr: 'Test',
        uk: 'Тестування',
        'zh-CN': '测试',
      },
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Descripción general',
            fr: "Vue d'ensemble",
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            pt: 'Visão geral',
            'pt-BR': 'Visão geral',
            'pt-PT': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'testing/overview',
        },
        {
          label: 'Write your first test',
          translations: {
            da: 'Skriv din første test',
            de: 'Schreibe deinen ersten Test',
            en: 'Write your first test',
            es: 'Escribe tu primera prueba',
            fr: 'Écrivez votre premier test',
            hi: 'अपना पहला परीक्षण लिखें',
            id: 'Tulis tes pertama Anda',
            it: 'Scrivi il tuo primo test',
            ja: '最初のテストを書く',
            ko: '첫 번째 테스트 작성',
            pt: 'Escreva seu primeiro teste',
            'pt-BR': 'Escreva seu primeiro teste',
            'pt-PT': 'Escreva o seu primeiro teste',
            ru: 'Напишите свой первый тест',
            tr: 'İlk testinizi yazın',
            uk: 'Напишіть свій перший тест',
            'zh-CN': '编写您的第一个测试',
          },
          slug: 'testing/write-your-first-test',
        },
        {
          label: 'Manage the AppHost in tests',
          translations: {
            da: 'Administrer AppHost i tests',
            de: 'Verwalten Sie den AppHost in Tests',
            en: 'Manage the AppHost in tests',
            es: 'Administrar el AppHost en pruebas',
            fr: "Gérer l'AppHost dans les tests",
            hi: 'परीक्षणों में AppHost प्रबंधित करें',
            id: 'Kelola AppHost dalam tes',
            it: "Gestisci l'AppHost nei test",
            ja: 'テストで AppHost を管理する',
            ko: '테스트에서 AppHost 관리',
            pt: 'Gerenciar o AppHost em testes',
            'pt-BR': 'Gerenciar o AppHost em testes',
            'pt-PT': 'Gerir o AppHost em testes',
            ru: 'Управление AppHost в тестах',
            tr: "Testlerde AppHost'u yönetin",
            uk: 'Керування AppHost у тестах',
            'zh-CN': '在测试中管理 AppHost',
          },
          slug: 'testing/manage-app-host',
        },
        {
          label: 'Access resources in tests',
          translations: {
            da: 'Få adgang til ressourcer i tests',
            de: 'Zugriff auf Ressourcen in Tests',
            en: 'Access resources in tests',
            es: 'Acceder a recursos en pruebas',
            fr: 'Accéder aux ressources dans les tests',
            hi: 'परीक्षणों में संसाधनों तक पहुंचें',
            id: 'Akses sumber daya dalam tes',
            it: 'Accedi alle risorse nei test',
            ja: 'テストでリソースにアクセスする',
            ko: '테스트에서 리소스 액세스',
            pt: 'Acessar recursos em testes',
            'pt-BR': 'Acessar recursos em testes',
            'pt-PT': 'Aceder a recursos em testes',
            ru: 'Доступ к ресурсам в тестах',
            tr: 'Testlerde kaynaklara erişin',
            uk: 'Доступ до ресурсів у тестах',
            'zh-CN': '在测试中访问资源',
          },
          slug: 'testing/accessing-resources',
        },
      ],
    },
    {
      label: 'Architecture',
      translations: {
        da: 'Arkitektur',
        de: 'Architektur',
        en: 'Architecture',
        es: 'Arquitectura',
        fr: 'Architecture',
        hi: 'आर्किटेक्चर',
        id: 'Arsitektur',
        it: 'Architettura',
        ja: 'アーキテクチャ',
        ko: '아키텍처',
        'pt-BR': 'Arquitetura',
        'pt-PT': 'Arquitetura',
        ru: 'Архитектура',
        tr: 'Mimari',
        uk: 'Архітектура',
        'zh-CN': '架构',
      },
      collapsed: true,
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Descripción general',
            fr: "Vue d'ensemble",
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            pt: 'Visão geral',
            'pt-BR': 'Visão geral',
            'pt-PT': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'architecture/overview',
        },
        {
          label: 'Resource model',
          translations: {
            da: 'Ressourcemodel',
            de: 'Ressourcenmodell',
            en: 'Resource model',
            es: 'Modelo de recurso',
            fr: 'Modèle de ressource',
            hi: 'संसाधन मॉडल',
            id: 'Model Sumber Daya',
            it: 'Modello di risorsa',
            ja: 'リソースモデル',
            ko: '리소스 모델',
            'pt-BR': 'Modelo de Recurso',
            'pt-PT': 'Modelo de Recurso',
            ru: 'Модель ресурса',
            tr: 'Kaynak Modeli',
            uk: 'Модель ресурсу',
            'zh-CN': '资源模型',
          },
          slug: 'architecture/resource-model',
        },
        {
          label: 'Resource hierarchies',
          translations: {
            da: 'Ressourcehierarkier',
            de: 'Ressourcenhierarchien',
            en: 'Resource hierarchies',
            es: 'Jerarquías de recursos',
            fr: 'Hiérarchies de ressources',
            hi: 'संसाधन पदानुक्रम',
            id: 'Hierarki Sumber Daya',
            it: 'Gerarchie delle risorse',
            ja: 'リソース階層',
            ko: '리소스 계층',
            'pt-BR': 'Hierarquias de Recursos',
            'pt-PT': 'Hierarquias de Recursos',
            ru: 'Иерархии ресурсов',
            tr: 'Kaynak Hiyerarşileri',
            uk: 'Ієрархії ресурсів',
            'zh-CN': '资源层次结构',
          },
          slug: 'architecture/resource-hierarchies',
        },
        {
          label: 'Resource API patterns',
          translations: {
            da: 'Ressource-API-mønstre',
            de: 'Ressource-API-Muster',
            en: 'Resource API patterns',
            es: 'Patrones de API de recursos',
            fr: "Modèles d'API de ressources",
            hi: 'संसाधन एपीआई पैटर्न',
            id: 'Pola API Sumber Daya',
            it: 'Modelli di API di risorse',
            ja: 'リソースAPIパターン',
            ko: '리소스 API 패턴',
            'pt-BR': 'Padrões de API de Recursos',
            'pt-PT': 'Padrões de API de Recursos',
            ru: 'Шаблоны API ресурсов',
            tr: 'Kaynak API Desenleri',
            uk: 'Шаблони API ресурсів',
            'zh-CN': '资源API模式',
          },
          slug: 'architecture/resource-api-patterns',
        },
        {
          label: 'Resource publishing',
          translations: {
            da: 'Ressourcepublicering',
            de: 'Ressourcenveröffentlichung',
            en: 'Resource publishing',
            es: 'Publicación de recursos',
            fr: 'Publication de ressources',
            hi: 'संसाधन प्रकाशन',
            id: 'Penerbitan Sumber Daya',
            it: 'Pubblicazione delle risorse',
            ja: 'リソースの公開',
            ko: '리소스 게시',
            'pt-BR': 'Publicação de Recursos',
            'pt-PT': 'Publicação de Recursos',
            ru: 'Публикация ресурсов',
            tr: 'Kaynak Yayınlama',
            uk: 'Публікація ресурсів',
            'zh-CN': '资源发布',
          },
          slug: 'architecture/resource-publishing',
        },
        {
          label: 'Resource examples',
          translations: {
            da: 'Ressourceeksempler',
            de: 'Ressourcenbeispiele',
            en: 'Resource examples',
            es: 'Ejemplos de recursos',
            fr: 'Exemples de ressources',
            hi: 'संसाधन उदाहरण',
            id: 'Contoh Sumber Daya',
            it: 'Esempi di risorse',
            ja: 'リソースの例',
            ko: '리소스 예제',
            'pt-BR': 'Exemplos de Recursos',
            'pt-PT': 'Exemplos de Recursos',
            ru: 'Примеры ресурсов',
            tr: 'Kaynak Örnekleri',
            uk: 'Приклади ресурсів',
            'zh-CN': '资源示例',
          },
          slug: 'architecture/resource-examples',
        },
        {
          label: 'Glossary',
          translations: {
            da: 'Ordbog',
            de: 'Glossar',
            en: 'Glossary',
            es: 'Glosario',
            fr: 'Glossaire',
            hi: 'शब्दावली',
            id: 'Kamus',
            it: 'Glossario',
            ja: '用語集',
            ko: '용어집',
            'pt-BR': 'Glossário',
            'pt-PT': 'Glossário',
            ru: 'Глоссарий',
            tr: 'Sözlük',
            uk: 'Глосарій',
            'zh-CN': '术语表',
          },
          slug: 'architecture/glossary',
        },
      ],
    },
  ],
};
