import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const integrationTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Integrations',
    es: 'Integraciones',
    fr: 'Intégrations',
    de: 'Integrationen',
    it: 'Integrazioni',
    pt: 'Integrações',
    ru: 'Интеграции',
    'zh-CN': '集成',
    da: 'Integrationer',
    hi: 'इंटीग्रेशन',
    id: 'Integrasi',
    ja: 'インテグレーション',
    ko: '통합',
    'pt-BR': 'Integrações',
    'pt-PT': 'Integrações',
    tr: 'Entegrasyonlar',
    uk: 'Інтеграції',
  },
  link: '/integrations/gallery',
  icon: 'puzzle',
  items: [
    {
      label: 'Explore',
      translations: {
        da: 'Udforsk',
        de: 'Entdecken',
        en: 'Explore',
        es: 'Explorar',
        fr: 'Explorer',
        hi: 'अन्वेषण',
        id: 'Jelajahi',
        it: 'Esplora',
        ja: '参照',
        ko: '탐색',
        pt: 'Explorar',
        'pt-BR': 'Explorar',
        'pt-PT': 'Explorar',
        ru: 'Исследовать',
        tr: 'Keşfet',
        uk: 'Дослідити',
        'zh-CN': '探索',
      },
      items: [
        {
          label: 'Integration gallery',
          translations: {
            da: 'Integrationsgalleri',
            de: 'Integrationsgalerie',
            en: 'Integration gallery',
            es: 'Galería de integraciones',
            fr: 'Galerie d’intégrations',
            hi: 'इंटीग्रेशन गैलरी',
            id: 'Galeri integrasi',
            it: 'Galleria delle integrazioni',
            ja: 'インテグレーションギャラリー',
            ko: '통합 갤러리',
            pt: 'Galeria de integrações',
            'pt-BR': 'Galeria de integrações',
            'pt-PT': 'Galeria de integrações',
            ru: 'Галерея интеграций',
            tr: 'Entegrasyon galerisi',
            uk: 'Галерея інтеграцій',
            'zh-CN': '集成图库',
          },
          slug: 'integrations/gallery',
        },
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Descripción general',
            fr: "Vue d'ensemble",
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            pt: 'Visão geral',
            'pt-BR': 'Visão geral',
            'pt-PT': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'integrations/overview',
        },
      ],
    },
    {
      label: 'Artificial Intelligence (AI)',
      collapsed: true,
      translations: {
        da: 'Kunstig intelligens (AI)',
        de: 'Künstliche Intelligenz (KI)',
        en: 'Artificial Intelligence (AI)',
        es: 'Inteligencia Artificial (IA)',
        fr: 'Intelligence Artificielle (IA)',
        hi: 'कृत्रिम बुद्धिमत्ता (एआई)',
        id: 'Kecerdasan Buatan (AI)',
        it: 'Intelligenza Artificiale (IA)',
        ja: '人工知能 (AI)',
        ko: '인공지능 (AI)',
        pt: 'Inteligência Artificial (IA)',
        'pt-BR': 'Inteligência Artificial (IA)',
        'pt-PT': 'Inteligência Artificial (IA)',
        ru: 'Искусственный интеллект (ИИ)',
        tr: 'Yapay Zeka (YZ)',
        uk: 'Штучний інтелект (ШІ)',
        'zh-CN': '人工智能 (AI)',
      },
      items: [
        { label: 'GitHub Models', slug: 'integrations/ai/github-models' },
        { label: 'Ollama', slug: 'integrations/ai/ollama' },
        { label: 'OpenAI', slug: 'integrations/ai/openai' },
      ],
    },
    {
      label: 'Custom integrations',
      collapsed: true,
      translations: {
        da: 'Brugerdefinerede integrationer',
        de: 'Benutzerdefinierte Integrationen',
        en: 'Custom integrations',
        es: 'Integraciones personalizadas',
        fr: 'Intégrations personnalisées',
        hi: 'कस्टम इंटीग्रेशन',
        id: 'Integrasi kustom',
        it: 'Integrazioni personalizzate',
        ja: 'カスタムインテグレーション',
        ko: '맞춤형 통합',
        pt: 'Integrações personalizadas',
        'pt-BR': 'Integrações personalizadas',
        'pt-PT': 'Integrações personalizadas',
        ru: 'Пользовательские интеграции',
        tr: 'Özel entegrasyonlar',
        uk: 'Користувацькі інтеграції',
        'zh-CN': '自定义集成',
      },
      items: [
        {
          label: 'Custom hosting',
          slug: 'integrations/custom-integrations/hosting-integrations',
          translations: {
            da: 'Brugerdefineret hosting',
            de: 'Benutzerdefiniertes Hosting',
            en: 'Custom hosting',
            es: 'Alojamiento personalizado',
            fr: 'Hébergement personnalisé',
            hi: 'कस्टम होस्टिंग',
            id: 'Hosting kustom',
            it: 'Hosting personalizzato',
            ja: 'カスタムホスティング',
            ko: '맞춤형 호스팅',
            pt: 'Hospedagem personalizada',
            'pt-BR': 'Hospedagem personalizada',
            'pt-PT': 'Hospedagem personalizada',
            ru: 'Пользовательский хостинг',
            tr: 'Özel barındırma',
            uk: 'Користувацький хостинг',
            'zh-CN': '自定义托管',
          },
        },
        {
          label: 'Custom clients',
          slug: 'integrations/custom-integrations/client-integrations',
          translations: {
            da: 'Brugerdefinerede klienter',
            de: 'Benutzerdefinierte Clients',
            en: 'Custom clients',
            es: 'Clientes personalizados',
            fr: 'Clients personnalisés',
            hi: 'कस्टम क्लाइंट',
            id: 'Klien kustom',
            it: 'Client personalizzati',
            ja: 'カスタムクライアント',
            ko: '맞춤형 클라이언트',
            pt: 'Clientes personalizados',
            'pt-BR': 'Clientes personalizados',
            'pt-PT': 'Clientes personalizados',
            ru: 'Пользовательские клиенты',
            tr: 'Özel istemciler',
            uk: 'Користувацькі клієнти',
            'zh-CN': '自定义客户端',
          },
        },
        {
          label: 'Secure communications',
          slug: 'integrations/custom-integrations/secure-communication',
          translations: {
            da: 'Sikre kommunikationer',
            de: 'Sichere Kommunikation',
            en: 'Secure communications',
            es: 'Comunicaciones seguras',
            fr: 'Communications sécurisées',
            hi: 'सुरक्षित संचार',
            id: 'Komunikasi aman',
            it: 'Comunicazioni sicure',
            ja: '安全な通信',
            ko: '보안 통신',
            pt: 'Comunicações seguras',
            'pt-BR': 'Comunicações seguras',
            'pt-PT': 'Comunicações seguras',
            ru: 'Безопасные коммуникации',
            tr: 'Güvenli iletişim',
            uk: 'Безпечні комунікації',
            'zh-CN': '安全通信',
          },
        },
      ],
    },
    {
      label: 'Cloud providers',
      collapsed: true,
      translations: {
        da: 'Cloud-udbydere',
        de: 'Cloud-Anbieter',
        en: 'Cloud providers',
        es: 'Proveedores de la nube',
        fr: 'Fournisseurs de cloud',
        hi: 'क्लाउड प्रदाता',
        id: 'Penyedia Cloud',
        it: 'Provider Cloud',
        ja: 'クラウドプロバイダー',
        ko: '클라우드 제공업체',
        pt: 'Provedores de Nuvem',
        'pt-BR': 'Provedores de Nuvem',
        'pt-PT': 'Provedores de Nuvem',
        ru: 'Облачные провайдеры',
        tr: 'Bulut Sağlayıcıları',
        uk: 'Хмарні провайдери',
        'zh-CN': '云提供商',
      },
      items: [
        {
          label: 'AWS',
          link: 'https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/aspire-integrations.html',
        },
        {
          label: 'Azure',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'integrations/cloud/azure/overview' },
            {
              label: 'Customize Azure resources',
              slug: 'integrations/cloud/azure/customize-resources',
            },
            {
              label: 'Local Azure provisioning',
              slug: 'integrations/cloud/azure/local-provisioning',
            },
            {
              label: 'Configure Azure Container Apps',
              slug: 'integrations/cloud/azure/configure-container-apps',
            },
            {
              label: 'Azure AI',
              collapsed: true,
              items: [
                {
                  label: 'AI compatibility matrix',
                  slug: 'integrations/cloud/azure/ai-compatibility-matrix',
                },
                {
                  label: 'Azure AI Foundry',
                  slug: 'integrations/cloud/azure/azure-ai-foundry',
                },
                {
                  label: 'Azure AI Inference',
                  slug: 'integrations/cloud/azure/azure-ai-inference',
                },
                {
                  label: 'Azure AI Search',
                  slug: 'integrations/cloud/azure/azure-ai-search',
                },
                {
                  label: 'Azure OpenAI',
                  slug: 'integrations/cloud/azure/azure-openai',
                },
              ],
            },
            {
              label: 'Azure App Configuration',
              slug: 'integrations/cloud/azure/azure-app-configuration',
            },
            {
              label: 'Azure App Service',
              slug: 'integrations/cloud/azure/azure-app-service',
            },
            {
              label: 'Azure Cache for Redis',
              slug: 'integrations/cloud/azure/azure-cache-redis',
            },
            {
              label: 'Azure Container Registry',
              slug: 'integrations/cloud/azure/azure-container-registry',
            },
            {
              label: 'Azure Cosmos DB',
              slug: 'integrations/cloud/azure/azure-cosmos-db',
            },
            {
              label: 'Azure Event Hubs',
              slug: 'integrations/cloud/azure/azure-event-hubs',
            },
            {
              label: 'Azure Functions',
              slug: 'integrations/cloud/azure/azure-functions',
            },
            {
              label: 'Azure Key Vault',
              slug: 'integrations/cloud/azure/azure-key-vault',
            },
            {
              label: 'Azure PostgreSQL',
              slug: 'integrations/cloud/azure/azure-postgresql',
            },
            {
              label: 'Azure Service Bus',
              slug: 'integrations/cloud/azure/azure-service-bus',
            },
            {
              label: 'Azure SignalR Service',
              slug: 'integrations/cloud/azure/azure-signalr',
            },
            {
              label: 'Azure SQL Database',
              slug: 'integrations/cloud/azure/azure-sql-database',
            },
            {
              label: 'Azure Storage',
              collapsed: true,
              items: [
                {
                  label: 'Azure Storage Blobs',
                  slug: 'integrations/cloud/azure/azure-storage-blobs',
                },
                {
                  label: 'Azure Storage Queues',
                  slug: 'integrations/cloud/azure/azure-storage-queues',
                },
                {
                  label: 'Azure Storage Tables',
                  slug: 'integrations/cloud/azure/azure-storage-tables',
                },
              ],
            },
            {
              label: 'Azure Web PubSub',
              slug: 'integrations/cloud/azure/azure-web-pubsub',
            },
            {
              label: 'Azure Container App Jobs',
              slug: 'integrations/cloud/azure/container-app-jobs',
            },
            {
              label: 'User-assigned managed identity',
              slug: 'integrations/cloud/azure/user-assigned-identity',
            },
            {
              label: 'Manage role assignments',
              slug: 'integrations/cloud/azure/role-assignments',
            },
          ],
        },
      ],
    },
    {
      label: 'Caching & state',
      collapsed: true,
      translations: {
        da: 'Caching og tilstand',
        de: 'Caching & Zustand',
        en: 'Caching & state',
        es: 'Caché y estado',
        fr: 'Mise en cache et état',
        hi: 'कैशिंग और स्थिति',
        id: 'Caching & State',
        it: 'Caching e stato',
        ja: 'キャッシングと状態',
        ko: '캐싱 및 상태',
        pt: 'Cache e Estado',
        'pt-BR': 'Cache e Estado',
        'pt-PT': 'Cache e Estado',
        ru: 'Кэширование и состояние',
        tr: 'Önbellekleme ve Durum',
        uk: 'Кешування та стан',
        'zh-CN': '缓存与状态',
      },
      items: [
        {
          label: 'Redis',
          collapsed: true,
          items: [
            {
              label: 'Integration overview',
              slug: 'integrations/caching/redis',
            },
            {
              label: 'Community extensions',
              slug: 'integrations/caching/redis-extensions',
            },
          ],
        },
        {
          label: 'Redis Distributed Cache',
          slug: 'integrations/caching/redis-distributed',
        },
        {
          label: 'Redis Output Cache',
          slug: 'integrations/caching/redis-output',
        },
        { label: 'Valkey', slug: 'integrations/caching/valkey' },
        { label: 'Garnet', slug: 'integrations/caching/garnet' },
      ],
    },
    {
      label: 'Compute & hosting',
      collapsed: true,
      translations: {
        da: 'Compute og hosting',
        de: 'Compute & hosting',
        en: 'Compute & hosting',
        es: 'Computación y alojamiento',
        fr: 'Calcul et hébergement',
        hi: 'कंप्यूट और होस्टिंग',
        id: 'Komputasi & hosting',
        it: 'Calcolo e hosting',
        ja: 'コンピューティングとホスティング',
        ko: '컴퓨팅 및 호스팅',
        pt: 'Computação e hospedagem',
        'pt-BR': 'Computação e hospedagem',
        'pt-PT': 'Computação e alojamento',
        ru: 'Вычисления и хостинг',
        tr: 'Hesaplama ve Barındırma',
        uk: 'Обчислення та хостинг',
        'zh-CN': '计算与托管',
      },
      items: [
        { label: 'Docker', slug: 'integrations/compute/docker' },
        { label: 'Kubernetes', slug: 'integrations/compute/kubernetes' },
      ],
    },
    {
      label: 'Data & databases',
      collapsed: true,
      translations: {
        da: 'Database',
        de: 'Datenbank',
        en: 'Data & databases',
        es: 'Base de datos',
        fr: 'Base de données',
        hi: 'डेटाबेस',
        id: 'Basis Data',
        it: 'Database',
        ja: 'データベース',
        ko: '데이터베이스',
        pt: 'Banco de dados',
        'pt-BR': 'Banco de dados',
        'pt-PT': 'Base de dados',
        ru: 'База данных',
        tr: 'Veritabanı',
        uk: 'База даних',
        'zh-CN': '数据库',
      },
      items: [
        {
          label: 'Elasticsearch',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/elasticsearch/elasticsearch-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/elasticsearch/elasticsearch-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/elasticsearch/elasticsearch-client',
            },
          ],
        },
        {
          label: 'Entity Framework Core',
          items: [
            {
              label: 'Overview',
              slug: 'integrations/databases/efcore/overview',
            },
            {
              label: 'Apply migrations',
              slug: 'integrations/databases/efcore/migrations',
            },
            {
              label: 'Seed data',
              slug: 'integrations/databases/efcore/seed-database',
            },
            {
              label: 'Azure Cosmos DB',
              slug: 'integrations/databases/efcore/azure-cosmos-db',
            },
            {
              label: 'Azure PostgreSQL',
              slug: 'integrations/databases/efcore/azure-postgresql',
            },
            {
              label: 'Azure SQL',
              slug: 'integrations/databases/efcore/azure-sql',
            },
            {
              label: 'MySQL Pomelo',
              slug: 'integrations/databases/efcore/mysql',
            },
            {
              label: 'Oracle',
              collapsed: true,
              items: [
                {
                  label: 'Get started',
                  slug: 'integrations/databases/efcore/oracle/oracle-get-started',
                },
                {
                  label: 'Hosting integration (AppHost)',
                  slug: 'integrations/databases/efcore/oracle/oracle-host',
                },
                {
                  label: 'Client integration (Your app)',
                  slug: 'integrations/databases/efcore/oracle/oracle-client',
                },
              ],
            },
            {
              label: 'PostgreSQL',
              slug: 'integrations/databases/efcore/postgresql',
            },
            {
              label: 'SQL Server',
              slug: 'integrations/databases/efcore/sql-server',
            },
          ],
        },
        { label: 'KurrentDB', slug: 'integrations/databases/kurrentdb' },
        { label: 'Meilisearch', slug: 'integrations/databases/meilisearch' },
        {
          label: 'Milvus',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/milvus/milvus-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/milvus/milvus-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/milvus/milvus-client',
            },
          ],
        },
        {
          label: 'MongoDB',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/mongodb/mongodb-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/mongodb/mongodb-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/mongodb/mongodb-client',
            },
            {
              label: 'Community extensions',
              slug: 'integrations/databases/mongodb/mongodb-extensions',
            },
          ],
        },
        {
          label: 'MySQL',
          collapsed: true,
          items: [
            {
              label: 'Integration overview',
              slug: 'integrations/databases/mysql/mysql-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/mysql/mysql-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/mysql/mysql-client',
            },
            {
              label: 'Community extensions',
              slug: 'integrations/databases/mysql/mysql-extensions',
            },
          ],
        },
        {
          label: 'PostgreSQL',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/postgres/postgres-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/postgres/postgres-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/postgres/postgres-client',
            },
            {
              label: 'Community extensions',
              slug: 'integrations/databases/postgres/postgresql-extensions',
            },
          ],
        },
        {
          label: 'Qdrant',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/qdrant/qdrant-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/qdrant/qdrant-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/qdrant/qdrant-client',
            },
          ],
        },
        { label: 'RavenDB', slug: 'integrations/databases/ravendb' },
        {
          label: 'SQL Server',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/sql-server/sql-server-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/sql-server/sql-server-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/sql-server/sql-server-client',
            },
            {
              label: 'Community extensions',
              slug: 'integrations/databases/sql-server/sql-server-extensions',
            },
          ],
        },
        { 
          label: 'SQLite',
          collapsed: true,
          items: [
            {
              label: 'Get started',
              slug: 'integrations/databases/sqlite/sqlite-get-started',
            },
            {
              label: 'Hosting integration (AppHost)',
              slug: 'integrations/databases/sqlite/sqlite-host',
            },
            {
              label: 'Client integration (Your app)',
              slug: 'integrations/databases/sqlite/sqlite-client',
            },
          ],
        },
        { label: 'SurrealDB', slug: 'integrations/databases/surrealdb' },
      ],
    },
    {
      label: 'Frameworks & runtimes',
      collapsed: true,
      translations: {
        da: 'Frameworks og runtime-miljøer',
        de: 'Frameworks & Laufzeiten',
        en: 'Frameworks & runtimes',
        es: 'Frameworks y entornos de ejecución',
        fr: "Frameworks et environnements d'exécution",
        hi: 'फ्रेमवर्क और रनटाइम',
        id: 'Kerangka & Runtime',
        it: 'Framework e runtime',
        ja: 'フレームワークとランタイム',
        ko: '프레임워크 및 런타임',
        pt: 'Frameworks e Runtimes',
        'pt-BR': 'Frameworks e Runtimes',
        'pt-PT': 'Frameworks e Runtimes',
        ru: 'Фреймворки и среды выполнения',
        tr: 'Çerçeveler ve Çalışma Zamanları',
        uk: 'Фреймворки та середовища виконання',
        'zh-CN': '框架和运行时',
      },
      items: [
        { label: '.NET MAUI', slug: 'integrations/frameworks/maui' },
        { label: 'Bun apps', slug: 'integrations/frameworks/bun-apps' },
        { label: 'Dapr', slug: 'integrations/frameworks/dapr' },
        { label: 'Deno apps', slug: 'integrations/frameworks/deno-apps' },
        { label: 'Go apps', slug: 'integrations/frameworks/go-apps' },
        { label: 'Java', slug: 'integrations/frameworks/java' },
        { label: 'JavaScript', slug: 'integrations/frameworks/javascript' },
        { label: 'Node.js extensions', slug: 'integrations/frameworks/nodejs-extensions' },
        { label: 'Orleans', slug: 'integrations/frameworks/orleans' },
        { label: 'PowerShell', slug: 'integrations/frameworks/powershell' },
        { label: 'Python', slug: 'integrations/frameworks/python' },
        { label: 'Rust', slug: 'integrations/frameworks/rust' },
      ],
    },
    {
      label: 'Messaging & eventing',
      collapsed: true,
      translations: {
        da: 'Meddelelser',
        de: 'Messaging',
        en: 'Messaging & eventing',
        es: 'Mensajería',
        fr: 'Messagerie',
        hi: 'मैसेजिंग',
        id: 'Pengiriman Pesan',
        it: 'Messaggistica',
        ja: 'メッセージング',
        ko: '메시징',
        pt: 'Mensageria',
        'pt-BR': 'Mensageria',
        'pt-PT': 'Mensageria',
        ru: 'Обмен сообщениями',
        tr: 'Mesajlaşma',
        uk: 'Обмін повідомленнями',
        'zh-CN': '消息传递',
      },
      items: [
        {
          label: 'Apache Kafka',
          slug: 'integrations/messaging/apache-kafka',
        },
        { label: 'LavinMQ', slug: 'integrations/messaging/lavinmq' },
        { label: 'NATS', slug: 'integrations/messaging/nats' },
        { label: 'RabbitMQ', slug: 'integrations/messaging/rabbitmq' },
      ],
    },
    {
      label: 'Security & identity',
      collapsed: true,
      translations: {
        da: 'Sikkerhed og identitet',
        de: 'Sicherheit & Identität',
        en: 'Security & identity',
        es: 'Seguridad e identidad',
        fr: 'Sécurité et identité',
        hi: 'सुरक्षा और पहचान',
        id: 'Keamanan & Identitas',
        it: 'Sicurezza e identità',
        ja: 'セキュリティとアイデンティティ',
        ko: '보안 및 ID',
        pt: 'Segurança e Identidade',
        'pt-BR': 'Segurança e Identidade',
        'pt-PT': 'Segurança e Identidade',
        ru: 'Безопасность и идентификация',
        tr: 'Güvenlik ve Kimlik',
        uk: 'Безпека та ідентичність',
        'zh-CN': '安全与身份',
      },
      items: [{ label: 'Keycloak', slug: 'integrations/security/keycloak' }],
    },
    {
      label: 'Observability & logging',
      collapsed: true,
      translations: {
        da: 'Observerbarhed og logning',
        de: 'Beobachtbarkeit & Protokollierung',
        en: 'Observability & logging',
        es: 'Observabilidad y registro',
        fr: 'Observabilité et journalisation',
        hi: 'पर्यवेक्षण और लॉगिंग',
        id: 'Observabilitas & Logging',
        it: 'Osservabilità e registrazione',
        ja: '可観測性とログ記録',
        ko: '관측 가능성 및 로깅',
        pt: 'Observabilidade e Registro',
        'pt-BR': 'Observabilidade e Registro',
        'pt-PT': 'Observabilidade e Registo',
        ru: 'Наблюдаемость и ведение журналов',
        tr: 'Gözlemlenebilirlik ve Günlük Kaydı',
        uk: 'Спостережуваність та ведення журналів',
        'zh-CN': '可观察性与日志记录',
      },
      items: [{ label: 'Seq', slug: 'integrations/observability/seq' }],
    },
    {
      label: 'Reverse proxies & APIs',
      collapsed: true,
      translations: {
        da: "Reverse proxies & API'er",
        de: 'Reverse Proxies & APIs',
        en: 'Reverse proxies & APIs',
        es: 'Reverse proxies y APIs',
        fr: 'Reverse proxies et APIs',
        hi: 'रिवर्स प्रॉक्सी और एपीआई',
        id: 'Reverse Proxies & API',
        it: 'Reverse proxy e API',
        ja: 'リバースプロキシとAPI',
        ko: '리버스 프록시 및 API',
        pt: 'Reverse Proxies e APIs',
        'pt-BR': 'Reverse Proxies e APIs',
        'pt-PT': 'Reverse Proxies e APIs',
        ru: 'Обратные прокси и API',
        tr: "Ters Proxyler ve API'ler",
        uk: 'Зворотні проксі та API',
        'zh-CN': '反向代理和API',
      },
      items: [
        {
          label: 'YARP (Yet Another Reverse Proxy)',
          slug: 'integrations/reverse-proxies/yarp',
        },
      ],
    },
    {
      label: 'Dev tools & extensions',
      collapsed: true,
      translations: {
        da: 'Dev-værktøjer og udvidelser',
        de: 'Dev-Tools & Erweiterungen',
        en: 'Dev tools & extensions',
        es: 'Herramientas de desarrollo y extensiones',
        fr: 'Outils de développement et extensions',
        hi: 'डेव टूल्स और एक्सटेंशन',
        id: 'Alat & Ekstensi Dev',
        it: 'Strumenti di sviluppo ed estensioni',
        ja: '開発ツールと拡張機能',
        ko: '개발 도구 및 확장 프로그램',
        pt: 'Ferramentas e Extensões de Desenvolvimento',
        'pt-BR': 'Ferramentas e Extensões de Desenvolvimento',
        'pt-PT': 'Ferramentas e Extensões de Desenvolvimento',
        ru: 'Инструменты разработчика и расширения',
        tr: 'Geliştirici Araçları ve Uzantılar',
        uk: 'Інструменти розробника та розширення',
        'zh-CN': '开发工具和扩展',
      },
      items: [
        { label: 'Data API Builder', slug: 'integrations/devtools/dab' },
        { label: 'Dev Tunnels', slug: 'integrations/devtools/dev-tunnels' },
        { label: 'flagd', slug: 'integrations/devtools/flagd' },
        { label: 'goff', slug: 'integrations/devtools/goff' },
        { label: 'k6', slug: 'integrations/devtools/k6' },
        { label: 'MailPit', slug: 'integrations/devtools/mailpit' },
        {
          label: 'SQL Database Projects',
          slug: 'integrations/devtools/sql-projects',
        },
      ],
    },
  ],
};
