import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const referenceTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Reference',
    es: 'Referencia',
    fr: 'Référence',
    de: 'Referenz',
    it: 'Riferimento',
    pt: 'Referência',
    ru: 'Справочник',
    'zh-CN': '参考',
    da: 'Reference',
    hi: 'संदर्भ',
    id: 'Referensi',
    ja: 'リファレンス',
    ko: '참고 자료',
    'pt-BR': 'Referência',
    'pt-PT': 'Referência',
    tr: 'Referans',
    uk: 'Довідник',
  },
  link: '/reference/overview',
  icon: 'seti:json',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        pt: 'Visão geral',
        'pt-BR': 'Visão geral',
        'pt-PT': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'reference/overview',
    },
    {
      label: 'API reference',
      translations: {
        da: 'API reference',
        de: 'API-Referenz',
        en: 'API reference',
        es: 'Referencia de API',
        fr: "Référence de l'API",
        hi: 'एपीआई संदर्भ',
        id: 'Referensi API',
        it: "Riferimento all'API",
        ja: 'APIリファレンス',
        ko: 'API 참조',
        pt: 'Referência da API',
        'pt-BR': 'Referência da API',
        'pt-PT': 'Referência da API',
        ru: 'Справочник по API',
        tr: 'API referansı',
        uk: 'Довідник API',
        'zh-CN': 'API参考',
      },
      collapsed: false,
      items: [
        {
          label: 'Browse APIs',
          translations: {
            da: "Gennemse API'er",
            de: 'APIs durchsuchen',
            en: 'Browse APIs',
            es: 'Explorar API',
            fr: 'Parcourir les API',
            hi: 'एपीआई ब्राउज़ करें',
            id: 'Jelajahi API',
            it: 'Sfoglia API',
            ja: 'APIを参照する',
            ko: 'API 찾아보기',
            pt: 'Navegar pelas APIs',
            'pt-BR': 'Navegar pelas APIs',
            'pt-PT': 'Navegar pelas APIs',
            ru: 'Просмотр API',
            tr: "API'lere Göz Atın",
            uk: 'Перегляд API',
            'zh-CN': '浏览 API',
          },
          slug: 'reference/api/browser',
        },
      ],
    },
    {
      label: 'CLI reference',
      translations: {
        en: 'CLI reference',
        es: 'Referencia de CLI',
        fr: 'Référence CLI',
        de: 'CLI-Referenz',
        it: 'Riferimento CLI',
        pt: 'Referência de CLI',
        ru: 'Справочник CLI',
        'zh-CN': 'CLI 参考',
        da: 'CLI-reference',
        hi: 'CLI संदर्भ',
        id: 'Referensi CLI',
        ja: 'CLI リファレンス',
        ko: 'CLI 참고서',
        'pt-BR': 'Referência de CLI',
        'pt-PT': 'Referência de CLI',
        tr: 'CLI referansı',
        uk: 'CLI Довідник',
      },
      collapsed: false,
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Descripción general',
            fr: "Vue d'ensemble",
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            pt: 'Visão geral',
            'pt-BR': 'Visão geral',
            'pt-PT': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'reference/cli/overview',
        },
        {
          label: 'Install script',
          translations: {
            da: 'Installationsscript',
            de: 'Installationsskript',
            en: 'Install script',
            es: 'Script de instalación',
            fr: "Script d'installation",
            hi: 'इंस्टॉलेशन स्क्रिप्ट',
            id: 'Skrip Instalasi',
            it: 'Script di installazione',
            ja: 'インストールスクリプト',
            ko: '설치 스크립트',
            pt: 'Script de instalação',
            'pt-BR': 'Script de instalação',
            'pt-PT': 'Script de instalação',
            ru: 'Скрипт установки',
            tr: 'Kurulum Betiği',
            uk: 'Скрипт установки',
            'zh-CN': '安装脚本',
          },
          slug: 'reference/cli/install-script',
        },
        {
          label: 'Configuration',
          translations: {
            da: 'Konfiguration',
            de: 'Konfiguration',
            en: 'Configuration',
            es: 'Configuración',
            fr: 'Configuration',
            hi: 'कॉन्फ़िगरेशन',
            id: 'Konfigurasi',
            it: 'Configurazione',
            ja: '構成',
            ko: '구성',
            pt: 'Configuração',
            'pt-BR': 'Configuração',
            'pt-PT': 'Configuração',
            ru: 'Конфигурация',
            tr: 'Yapılandırma',
            uk: 'Конфігурація',
            'zh-CN': '配置',
          },
          slug: 'reference/cli/configuration',
        },
        {
          label: 'Commands',
          translations: {
            da: 'Kommandoer',
            de: 'Befehle',
            en: 'Commands',
            es: 'Comandos',
            fr: 'Commandes',
            hi: 'कमांड',
            id: 'Perintah',
            it: 'Comandi',
            ja: 'コマンド',
            ko: '명령어',
            pt: 'Comandos',
            'pt-BR': 'Comandos',
            'pt-PT': 'Comandos',
            ru: 'Команды',
            tr: 'Komutlar',
            uk: 'Команди',
            'zh-CN': '命令',
          },
          collapsed: true,
          items: [
            { label: 'aspire', slug: 'reference/cli/commands/aspire' },
            { label: 'aspire add', slug: 'reference/cli/commands/aspire-add' },
            {
              label: 'aspire cache',
              collapsed: true,
              items: [
                {
                  label: 'aspire cache',
                  slug: 'reference/cli/commands/aspire-cache',
                },
                {
                  label: 'aspire cache clear',
                  slug: 'reference/cli/commands/aspire-cache-clear',
                },
              ],
            },
            {
              label: 'aspire config',
              collapsed: true,
              items: [
                {
                  label: 'aspire config',
                  slug: 'reference/cli/commands/aspire-config',
                },
                {
                  label: 'aspire config list',
                  slug: 'reference/cli/commands/aspire-config-list',
                },
                {
                  label: 'aspire config get',
                  slug: 'reference/cli/commands/aspire-config-get',
                },
                {
                  label: 'aspire config set',
                  slug: 'reference/cli/commands/aspire-config-set',
                },
                {
                  label: 'aspire config delete',
                  slug: 'reference/cli/commands/aspire-config-delete',
                },
              ],
            },
            {
              label: 'aspire deploy',
              slug: 'reference/cli/commands/aspire-deploy',
            },
            { label: 'aspire do', slug: 'reference/cli/commands/aspire-do' },
            {
              label: 'aspire doctor',
              slug: 'reference/cli/commands/aspire-doctor',
            },
            { label: 'aspire exec', slug: 'reference/cli/commands/aspire-exec' },
            { label: 'aspire init', slug: 'reference/cli/commands/aspire-init' },
            {
              label: 'aspire mcp',
              collapsed: true,
              items: [
                {
                  label: 'aspire mcp',
                  slug: 'reference/cli/commands/aspire-mcp',
                },
                {
                  label: 'aspire mcp init',
                  slug: 'reference/cli/commands/aspire-mcp-init',
                },
                {
                  label: 'aspire mcp start',
                  slug: 'reference/cli/commands/aspire-mcp-start',
                },
              ],
            },
            { label: 'aspire new', slug: 'reference/cli/commands/aspire-new' },
            {
              label: 'aspire publish',
              slug: 'reference/cli/commands/aspire-publish',
            },
            { label: 'aspire run', slug: 'reference/cli/commands/aspire-run' },
            {
              label: 'aspire update',
              slug: 'reference/cli/commands/aspire-update',
            },
          ],
        },
      ],
    },
  ],
};
